config/routes.rb
DealRedemptions::Engine.routes.draw do
  root to: 'welcome#index'

  # Redemptions
  scope :voucher do
    get ':company', to: 'redeem#new', as: :redemption
    post ':company', to: 'redeem#create'
  end

  get 'thankyou', to: 'redeem#thankyou', as: :thank_you

  get 'validate/code/:company/:code', to: 'redeem#validate_code', as: :validate_redeem_code

  # Admin
  namespace :admin, constraints: DealRedemptions::AdminInterfaceDomain.new do
    #get '/', to: 'dashboard#index', as: 'dashboard'
    get '/', to: 'redemptions#index', as: 'home'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    scope :settings do
      get '', to: 'settings#index', as: 'settings'
      put 'password', to: 'settings#change_admin_password'
    end

    scope :transfer do
      get '', to: 'import#new', as: 'import'
      post '', to: 'import#create'
      get 'export_redemptions', to: 'import#export_redemptions', as: :export_redemptions
    end

    resources :user
    resources :companies
    resources :redemptions
    resources :products, except: [:show]
    resources :redeem_codes, except: [:show]
    resources :sessions
  end
end

app/models/deal_redemptions/redeem_code.rb
module DealRedemptions
  class RedeemCode < ActiveRecord::Base
    belongs_to :company
    belongs_to :product
    belongs_to :redemption

    validates :code, presence: true

    scope :redeemed, -> { where(status: 2) }

    enum status: { void: 0, active: 1, redeemed: 2 }

    # Validate redemption code as an active voucher
    def validate_code(params)
      if self.company.slug == params[:company] && self.active?
        true
      else
        false
      end
    end

    def self.find_all_by_code(codes=[])
      where(code: codes)
    end

    def self.by_company(company)
      where(company_id: company)
    end

    # Find code and company
    def self.find_code_and_company(code, company)
      where("code = ? AND company_id = ?", code, company)
    end
  end
end

app/controllers/deal_redemptions/admin/redeem_codes_controller.rb
require_dependency "deal_redemptions/application_controller"

module DealRedemptions
  class Admin::RedeemCodesController < ApplicationController
    layout 'deal_redemptions/admin/default'

    before_action :admin_authorize
    before_action :set_admin_redeem_code, only: [:edit, :update, :destroy]
    before_action :check_existing_company_code, only: [:update, :create]

    # GET /admin/redeem_codes
    def index
      # Check if search param is present
      if params[:search].blank?
        @admin_redeem_codes = DealRedemptions::RedeemCode.page(params[:page]).order(:code).includes(:company)
      else
        query = DealRedemptions::Redemption.find_by_sql(build_search_query)
        @admin_redeem_codes = Kaminari.paginate_array(query).page(params[:page])
      end
    end

    # GET /admin/redeem_codes/new
    def new
      @admin_redeem_code = DealRedemptions::RedeemCode.new
    end

    # GET /admin/redeem_codes/1/edit
    def edit
    end

    # POST /admin/redeem_codes
    def create
      @admin_redeem_code = DealRedemptions::RedeemCode.new(redeem_code_params)

      if @existing_code.count > 0
        flash[:notice] = 'Redemption code already exists.'
        render :new
      else
        if @admin_redeem_code.save
          redirect_to admin_redeem_codes_path, notice: 'Redeem code was successfully created.'
        else
          render :new
        end
      end
    end

    # PATCH/PUT /admin/redeem_codes/1
    def update
      if @existing_code.count > 0
        flash[:notice] = 'Redemption code already exists.'
        render :edit
      else
        if @admin_redeem_code.update(redeem_code_params)
          redirect_to admin_redeem_codes_path, notice: 'Redeem code was successfully updated.'
        else
          render :edit
        end
      end
    end

    # DELETE /admin/redeem_codes/1
    def destroy
      @admin_redeem_code.destroy
      redirect_to admin_redeem_codes_url, notice: 'Redeem code was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_redeem_code
        @admin_redeem_code = DealRedemptions::RedeemCode.find(params[:id])
      end

      # Check existing redemption code by company
      def check_existing_company_code
        redeem_code = params[:redeem_code]
        @existing_code = DealRedemptions::RedeemCode.find_code_and_company(redeem_code[:code], redeem_code[:company_id])
      end

      # Search redemption codes
      def build_search_query
        string = params[:search].split ' '
        redeem_codes = DealRedemptions::RedeemCode.arel_table
        companies = DealRedemptions::Company.arel_table
        query = redeem_codes.project(
          redeem_codes[:id],
          redeem_codes[:company_id],
          redeem_codes[:code],
          redeem_codes[:status],
          redeem_codes[:created_at]
        )
        .join(companies)
        .on(redeem_codes[:company_id]
            .eq(companies[:id]))

        string.each do |s|
          query.where(redeem_codes[:code].matches("%#{s}%"))
        end

        query.to_sql
      end

      # Only allow a trusted parameter "white list" through.
      def redeem_code_params
        params.require(:redeem_code).permit(:company_id, :product_id, :code, :status)
      end
  end
end

app/views/deal_redemptions/admin/redeem_codes/_form.html.haml
- if @admin_redeem_code.errors.any?
  .alert.alert-danger
    %ul
    - @admin_redeem_code.errors.full_messages.each do |msg|
      %li
        = msg

= form_for [:admin, @admin_redeem_code] do |f|
  .form-group
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .form-group
    = f.label :company_id, 'Company'
    = f.select :company_id, DealRedemptions::Company.all_by_name.collect {|c| [c.name, c.id]}, {}, { class: 'form-control' }
  .form-group
    = f.label :product_id, 'Product'
    = f.select :product_id, DealRedemptions::Product.all.collect {|p| [p.name, p.id]}, {}, { class: 'form-control' }
  .form-group
    = f.label :status
    = f.select :status, [:active, :redeemed, :void], {}, { class: 'form-control' }
  .form-group.pull-right
    = f.submit @admin_redeem_code.new_record? ? "Create Code" : "Edit Code", class: 'btn btn-primary'

app/views/deal_redemptions/admin/redeem_codes/edit.html.haml
- page_title "Redemption Code"
- admin_page_title "<i class=\"redemptions\"></i> #{link_to 'Redemption Codes', admin_redeem_code_path} / #{@admin_redeem_code.code}".html_safe

.row
  .col-md-4
    %h3 Edit existing redemption code
    Make modifications to an existing redemption code.
    %hr

    - unless @admin_redeem_code.redemption_id.blank?
      %h4 This code has been used.
      = link_to 'View Redemption', admin_redemption_path(@admin_redeem_code.redemption_id)
      %hr

    %h4 Want to remove this code?
    %h5 Click the button below. You can <strong>NOT</strong> undo this action.

    = button_to 'Delete Redeem Code', admin_redeem_code_path, method: :delete, name: nil, class: 'btn btn-danger', onclick: 'if(!confirm("Are you sure you want to delete this redemption code?")) return false;'
    %hr

  .col-md-8
    = render 'form'

app/views/deal_redemptions/admin/redeem_codes/index.html.haml
- page_title 'Redemption Codes'
- admin_page_title '<i class="redemptions"></i> Redemption Codes'.html_safe

%hr
  .row.clearfix
    .col-md-4
      = form_tag '', method: 'get', class: 'search-redemptions pull-right' do
        .col-md-8.padding-right-5
          .form-group
            = search_field_tag '', '', name: 'search', class: 'form-control', placeholder: 'Search by code:'
        .col-md-4.padding-left-5
          .form-group
            = button_tag 'Search', name: nil, class: 'btn btn-primary'
    .col-md-8
%hr

- if @admin_redeem_codes.empty?

  .no-current-redemptions
    %i.redemptions.clearfix
    No redemption codes were found

- else
  .row
    .col-md-12
      = link_to 'New Code', new_admin_redeem_code_path, class: 'btn btn-primary pull-right'
  %hr

  = paginate @admin_redeem_codes

  %table{id: 'redemptions', class: 'table default'}
    %thead
      %tr
        %td
          Code
        %td
          Company:
        %td
          Status:
        %td
          Created:
    %tbody
    - @admin_redeem_codes.each do |code|
      %tr
        %td
          = link_to "#{code.code}", edit_admin_redeem_code_path(code.id)
        %td
          = code.company.name
        %td
          = code.status
        %td
          = code.created_at

  .row-fluid
    = paginate @admin_redeem_codes

app/views/deal_redemptions/admin/redeem_codes/new.html.haml
- page_title "New Redemption Code"
- admin_page_title "<i class=\"redemptions\"></i> #{link_to 'Redeem Codes', admin_redeem_codes_path} / New Redeem Code".html_safe

.row
  .col-md-4
    %h3 New redemption code
    Add new deal site redemption code.
    %hr

  .col-md-8
    = render 'form'