config/routes.rb
DealRedemptions::Engine.routes.draw do
  root to: 'welcome#index'

  # Redemptions
  scope :voucher do
    get ':company', to: 'redeem#new', as: :redemption
    post ':company', to: 'redeem#create'
  end

  get 'thankyou', to: 'redeem#thankyou', as: :thank_you

  get 'validate/code/:company/:code', to: 'redeem#validate_code', as: :validate_redeem_code

  # Admin
  namespace :admin, constraints: DealRedemptions::AdminInterfaceDomain.new do
    #get '/', to: 'dashboard#index', as: 'dashboard'
    get '/', to: 'redemptions#index', as: 'home'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    scope :settings do
      get '', to: 'settings#index', as: 'settings'
      put 'password', to: 'settings#change_admin_password'
    end

    scope :transfer do
      get '', to: 'import#new', as: 'import'
      post '', to: 'import#create'
      get 'export_redemptions', to: 'import#export_redemptions', as: :export_redemptions
    end

    resources :user
    resources :companies
    resources :redemptions
    resources :products, except: [:show]
    resources :redeem_codes, except: [:show]
    resources :sessions
  end
end

app/models/deal_redemptions/product.rb
module DealRedemptions
  class Product < ActiveRecord::Base
    has_many :redeem_code

    before_validation :format_url_protocol
    validates :name, presence: true

    private

    def format_url_protocol
      if self.url.present?
        unless self.url[/^http:\/\//] || self.url[/^https:\/\//]
          self.url = "http://#{self.url}"
        end
      end
    end
  end
end

app/controllers/deal_redemptions/admin/products_controller.rb
require_dependency "deal_redemptions/application_controller"

module DealRedemptions
  class Admin::ProductsController < ApplicationController
    layout '/deal_redemptions/admin/default'

    before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

    # GET /admin/products
    def index
      @products = Product.page(params[:page])
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit
    end

    # POST /admin/products
    def create
      @product = Product.new(admin_product_params)

      if @product.save
        redirect_to admin_products_path, notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/products/1
    def update
      if @product.update(admin_product_params)
        redirect_to admin_products_path, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/products/1
    def destroy
      @product.destroy
      redirect_to admin_products_path, notice: 'Product was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_product
        @product = Product.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def admin_product_params
        params.require(:product).permit(:name, :url)
      end
  end
end

app/views/deal_redemptions/admin/products/_form.html.haml
- if @product.errors.any?
  .alert.alert-danger
    %ul
    - @product.errors.full_messages.each do |msg|
      %li
        = msg

= form_for [:admin, @product] do |f|
  .form-group
    = f.label :name, 'Name:'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :url, 'URL:'
    = f.text_field :url, class: 'form-control'
  .form-group.pull-right
    = f.submit @product.new_record? ? "Create Product" : "Edit Product", class: 'btn btn-primary'

app/views/deal_redemptions/admin/products/edit.html.haml
- page_title "#{@product.name}"
- admin_page_title "<i class=\"products\"></i> #{link_to 'Products', admin_products_path} / #{@product.name}".html_safe

.row
  .col-md-4
    %h3 Edit existing product
    Make modifications to an existing product.
    %hr

    %h4 Want to remove this product?
    %h5 Click the button below. You can <strong>NOT</strong> undo this action.

    = button_to 'Delete Product', admin_product_path, method: :delete, class: 'btn btn-danger', onclick: 'if(!confirm("Are you sure you want to delete this product?")) return false;'
    %hr


  .col-md-8
    = render 'form'

app/views/deal_redemptions/admin/products/index.html.haml
- page_title 'Products'
- admin_page_title '<i class="products"></i> Products'.html_safe

.row
  .col-md-12
    = link_to 'New Product', new_admin_product_path, class: 'btn btn-primary pull-right'
%hr

- if @products.count > 0
  %table{class: 'table default'}
    %thead
      %tr
        %td
          Name:
    %tbody
    - @products.each do |c|
      %tr
        %td
          = link_to c.name, edit_admin_product_path(c.id)

  = paginate @products

- else
  .no-current-products
    %i.products.clearfix
    No Current Products

app/views/deal_redemptions/admin/products/new.html.haml
- page_title "New Product"
- admin_page_title "<i class=\"products\"></i> #{link_to 'Products', admin_products_path} / New Product".html_safe

.row
  .col-md-4
    %h3 New product
    Add new product to track with redemption codes
    %hr

  .col-md-8
    = render 'form'