config/routes.rb
DealRedemptions::Engine.routes.draw do
  root to: 'welcome#index'

  # Redemptions
  scope :voucher do
    get ':company', to: 'redeem#new', as: :redemption
    post ':company', to: 'redeem#create'
  end

  get 'thankyou', to: 'redeem#thankyou', as: :thank_you

  get 'validate/code/:company/:code', to: 'redeem#validate_code', as: :validate_redeem_code

  # Admin
  namespace :admin, constraints: DealRedemptions::AdminInterfaceDomain.new do
    #get '/', to: 'dashboard#index', as: 'dashboard'
    get '/', to: 'redemptions#index', as: 'home'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    scope :settings do
      get '', to: 'settings#index', as: 'settings'
      put 'password', to: 'settings#change_admin_password'
    end

    scope :transfer do
      get '', to: 'import#new', as: 'import'
      post '', to: 'import#create'
      get 'export_redemptions', to: 'import#export_redemptions', as: :export_redemptions
    end

    resources :user
    resources :companies
    resources :redemptions
    resources :products, except: [:show]
    resources :redeem_codes, except: [:show]
    resources :sessions
  end
end

app/models/deal_redemptions/company.rb
module DealRedemptions
  class Company < ActiveRecord::Base
    has_many :redemption
    has_many :redeem_code

    before_validation :format_url_protocol

    validates :name, :slug, presence: true, uniqueness: true

    scope :active_by_name, -> { where(active: 1).order(:name) }
    scope :all_by_name, -> { all.order(:name) }

    def self.find_active
      where(active: 1)
    end

    private

    def format_url_protocol
      if self.url.present?
        unless self.url[/^http:\/\//] || self.url[/^https:\/\//]
          self.url = "http://#{self.url}"
        end
      end
    end
  end
end

app/controllers/deal_redemptions/admin/companies_controller.rb
require_dependency "deal_redemptions/application_controller"

module DealRedemptions
  class Admin::CompaniesController < ApplicationController
    layout '/deal_redemptions/admin/default'
    rescue_from ActiveRecord::RecordNotFound, with: :redirect_to_companies

    before_action :admin_authorize
    before_action :set_company, only: [:show, :edit, :update, :destroy]

    def index
      @companies = DealRedemptions::Company.all_by_name.page(params[:page])
    end

    def new
      @company = DealRedemptions::Company.new
    end

    def create
      @company = DealRedemptions::Company.new(company_params)

      if @company.save
        redirect_to admin_companies_path, notice: 'Company successfully added.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @company.update(company_params)
        redirect_to admin_companies_path, notice: 'Company was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      if @company.destroy
        redirect_to admin_companies_path, notice: 'Company was successfully removed.'
      else
        render :edit, notice: 'Company was not removed. Try again'
      end
    end

    protected

      def redirect_to_companies
        redirect_to admin_companies_path
      end

    private

      # Use callbacks to share common setup or constraints between actions.
      def set_company
        @company = DealRedemptions::Company.find(params[:id])
      end

      def company_params
        # Whitelist permitted parameters
        params.require(:company).permit(:name, :description, :url, :slug, :active)
      end
  end
end

app/views/deal_redemptions/admin/companies/_form.html.haml
- if @company.errors.any?
  .alert.alert-danger
    %ul
    - @company.errors.full_messages.each do |msg|
      %li
        = msg

= form_for [:admin, @company] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 10
  .form-group
    = f.label :url, 'URL'
    = f.text_field :url, class: 'form-control'
  .form-group
    = f.label :slug
    = f.text_field :slug, class: 'form-control'
  .form-group
    = f.label :active, 'Current Active'
    = f.select :active, [['Yes', 1], ['No', 0]], {}, { class: 'form-control' }
  .form-group.pull-right
    = f.submit @company.new_record? ? "Create Company" : "Edit Company", class: 'btn btn-primary'

app/views/deal_redemptions/admin/companies/edit.html.haml
- page_title "#{@company.name}"
- admin_page_title "<i class=\"companies\"></i> #{link_to 'Companies', admin_companies_path} / #{@company.name}".html_safe

.row
  .col-md-4
    %h3 Edit existing company
    Make modifications to an existing deal site.
    %hr

    %h4 Want to remove this company?
    %h5 Click the button below. You can <strong>NOT</strong> undo this action.
    %h5 You can make a company unactive so customers can't redeem as an alternative.

    = button_to 'Delete Company', admin_company_path, method: :delete, class: 'btn btn-danger', onclick: 'if(!confirm("Are you sure you want to delete this company?")) return false;'
    %hr


  .col-md-8
    = render 'form'

app/views/deal_redemptions/admin/companies/index.html.haml
- page_title 'Companies'
- admin_page_title '<i class="companies"></i> Companies'.html_safe

.row
  .col-md-12
    = link_to 'New Company', new_admin_company_path, class: 'btn btn-primary pull-right'
%hr

%table{class: 'table default'}
  %thead
    %tr
      %td
        Name:
      %td
        URL:
      %td
        Slug:
      %td
        Active:
  %tbody
  - @companies.each do |c|
    %tr
      %td
        = link_to c.name, edit_admin_company_path(c.id)
      %td
        = c.url
      %td
        = c.slug
      %td
        = c.active == 1 ? 'Yes' : 'No'

= paginate @companies

app/views/deal_redemptions/admin/companies/new.html.haml
- page_title "New Company"
- admin_page_title "<i class=\"companies\"></i> #{link_to 'Companies', admin_companies_path} / New Company".html_safe

.row
  .col-md-4
    %h3 New company
    Add new deal site for customers to redeem.
    %hr

  .col-md-8
    = render 'form'