config/routes.rb
DealRedemptions::Engine.routes.draw do
  root to: 'welcome#index'

  # Redemptions
  scope :voucher do
    get ':company', to: 'redeem#new', as: :redemption
    post ':company', to: 'redeem#create'
  end

  get 'thankyou', to: 'redeem#thankyou', as: :thank_you

  get 'validate/code/:company/:code', to: 'redeem#validate_code', as: :validate_redeem_code

  # Admin
  namespace :admin, constraints: DealRedemptions::AdminInterfaceDomain.new do
    #get '/', to: 'dashboard#index', as: 'dashboard'
    get '/', to: 'redemptions#index', as: 'home'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    scope :settings do
      get '', to: 'settings#index', as: 'settings'
      put 'password', to: 'settings#change_admin_password'
    end

    scope :transfer do
      get '', to: 'import#new', as: 'import'
      post '', to: 'import#create'
      get 'export_redemptions', to: 'import#export_redemptions', as: :export_redemptions
    end

    resources :user
    resources :companies
    resources :redemptions
    resources :products, except: [:show]
    resources :redeem_codes, except: [:show]
    resources :sessions
  end
end

app/views/deal_redemptions/admin/shared/_sidebar.html.haml
%section.sidebar
  .account-header
    %p{class: 'site-name'}= site_name(DealRedemptions.config.site_name)

  %nav{class: 'main'}
    %ul
      %li
        = admin_link_to('<i class="redemptions"></i> Redemptions'.html_safe, admin_redemptions_path, {class: 'sidebar-link'})
      %li
        = admin_link_to('<i class="products"></i> Products'.html_safe, admin_products_path, {class: 'sidebar-link'})
      %li
        = admin_link_to('<i class="companies"></i> Companies'.html_safe, admin_companies_path, {class: 'sidebar-link'})
      %li
        = admin_link_to('<i class="redemptions"></i> Redeem Codes'.html_safe, admin_redeem_codes_path, {class: 'sidebar-link'})
      %li
        = admin_link_to('<i class="import"></i> Import/Export'.html_safe, admin_import_path, {class: 'sidebar-link'})
      %li
        = admin_link_to('<i class="settings"></i> Settings'.html_safe, admin_settings_path, {class: 'sidebar-link'})

app/views/deal_redemptions/admin/shared/_topbar.html.haml
.topbar
  %h1= yield(:admin_page_title)

  .pull-right
    = link_to 'Logout', admin_logout_path, class: 'btn btn-info' if current_admin_user